### ISSUE TITLE
Qsearch shift click sending to wrong slots

### ISSUE THREAD

**Issue by KryptonCaptain** [bt2901/unraveling#4]
Shift-clicked an item into the Quaesitum, all fine. Tried to shift-click it out, and it moved to the output slot. Does not move further from there.

![image](https://user-images.githubusercontent.com/8790829/28164075-f786d7ca-6810-11e7-837b-5608291e0493.png)

Also, you can scrutinise scrutiny reports, so maybe an internal blacklist for certain things might not be the worst
![image](https://user-images.githubusercontent.com/8790829/28164170-75a56bc6-6811-11e7-8b32-e5b48d6bc547.png)

**Comment by bt2901** [comment]
> Also, you can scrutinise scrutiny reports, so maybe an internal blacklist for certain things might not be the worst

This is intentional: I plan to add an ability to extract useful info from Scrutiny Reports and Research Notes (if player has "SCRUTINY_INTUITION" and/or "SCRUTINY_RECYCLING" research completed). However, this isn't implemented yet (working on it now).

Will look into shift-clicking, thank you.

**Comment by bt2901** [comment]
Scrutinising scrutiny reports and research notes should be working now (I'm not sure if it's balanced, but you can discover all aspects without using a research table even once!). Also, there's a chance of research failure and consuming the item. 

Shift+click almost works: it transfers items up, but sometimes it dupes them. Need to fix this properly. 

While we are at it, I need to check that scrutinising coal block is possible (for some mysterious reason, it wasn't before)
